name: Deploy Backend to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PI_HOST }}
          username: pi
          key: ${{ secrets.PI_SSH_KEY }}
          port: 22
          script: |
            cd ~/github/News-app-BE
            git pull origin main
            npm install
            pm2 restart news-app || pm2 start listen.js --name news-app
