name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Pi over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PI_HOST }}
          username: simon
          key: ${{ secrets.PI_SSH_KEY }}
          port: 23704
          script: |
            cd ~/News-app-BE
            git pull origin main
            npm install
            npm run build
            sudo rm -rf /var/www/html/News-app-BE/*
            sudo cp -r dist/* /var/www/html/News-app-BE/
